### ISSUE TITLE
Ability to clear highlighting

### ISSUE THREAD

**Issue by rkdarst** [usefulaaltomapfi/usefulaaltomap#3]
When you select a single building, everything else should be un-highlighted.  For example, searching for and selecting a single building makes it a stronger outline.  Maybe this should un-highlight everything else.  Also, clearing highlighting will be important for other things, like dropping individual markers (maybe...).

**Comment by murhum1** [comment]
Added `mapService.clearHighlights()` in c9217f015f29a1536486d58c718757dbb40e610e.
